- hosts: all
  become: yes
  vars:
    - workshop_user: transcriptomics
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - software_dir: "/home/{{workshop_user}}/software"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"
    # sha-512 hash
    - genomics_user_password: $6$xsb/UrhJ$sxievieZ7erTF93MwiBEZqm/mIpTVlTd3uhYGY2Urt5qoGapG3ZEU6NrGMOYd7QUnFfXhgDn12OPxDuxb20dB0
    # mysql native hash - SELECT PASSWORD("password") - also need to set in stacks_web.yaml
    - stacks_user_password: '*39094635b39efded76637451cdbd294d41865007'
    # jupyter password https://jupyter-notebook.readthedocs.io/en/latest/public_server.html#preparing-a-hashed-password
    - jupyter_password: 'sha1:0909a8ee63e4:7c0d5e80d50acbdc07d9e7f3ac66d028713e2825'
    
  pre_tasks:
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create {{workshop_user}} Workshop User
      user: name="{{workshop_user}}" group=workshop comment="{{workshop_user}} Workshop User" state=present shell=/bin/bash password={{genomics_user_password}}
      
    # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner="{{workshop_user}}" group=workshop
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner="{{workshop_user}}" group=workshop
    - name: Create Workshop Directory
      file: path={{workshop_dir}} state=directory owner="{{workshop_user}}" group=workshop
      
    - name: Installing Some Other Build Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
       - libhdf5-cpp-11 #blasr
       - libhdf5-dev #blasr
       - libfreetype6-dev #matplotlib
       - python3-pip

    # a bunch of aliasses I like to include
    - include: software_tasks/profile.yaml
      tags: alias, profile
    
    - name: Changing hostname to "{{workshop_user}}"
      lineinfile: dest=/etc/hostname regexp="^ip.*" line="{{workshop_user}}"
      tags: hostname

    - name: Changing hosts to "{{workshop_user}}"
      lineinfile: dest=/etc/hosts regexp="^127.*" line="127.0.0.1 localhost {{workshop_user}}"
      tags: hostname

    - include: software_tasks/hostname.yaml
      tags: hostname

    - include: software_tasks/motd.yaml
      tags: motd

    - include: software_tasks/desktop.yaml
      tags: desktop

  tasks:
    ### Commonly Required Programs/Libraries ###
    # bamtools is only in Ubuntu repos from 16.04+
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
       - sra-toolkit
      tags: general, alignment, assembly, genomics, seqdqc, transcriptomics, differential

    - name: Installing BioPerl - slow
      cpanm: name=CJFIELDS/BioPerl-1.6.924.tar.gz
      tags: general, alignment, assembly, genomics, seqdqc, bioperl

    - name: Installing BioPython
      pip: name=biopython state=present
      tags: general, alignment, assembly, genomics, seqdqc, biopython
    
    # Conda for Python 2.7
    #- include: software_tasks/conda.yaml version=2 prefix=/home/genomics/miniconda
    #  tags: general, conda, qiime, qiime2

    # Conda for Python 3.0
    - include: software_tasks/conda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, qiime, qiime2

    # Add Bioconda repos for Conda with Python 3
    - include: software_tasks/bioconda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, bioconda, qiime, qiime2

    ### Unix ###
    # Base is OK

    - name: Installing cutadapt
      pip: name=cutadapt state=present
      tags: cutadapt

    - name: Install ea-utils 1.04.676, trimmomatic
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
      tags: trimmomatic, ea-utils
      
    # The Ubuntu fastqc package is broken!
    - include: software_tasks/fastqc.yaml version=0.11.5
      tags: fastqc

    - name: Installing vcftools
      apt: name=vcftools state=present
      tags: vcftools

    # installs bowtie 1 and 2
    - include: software_tasks/bowtie.yaml version=2.2.9
      tags: bowtie, transcriptomics

    - include: software_tasks/bwa.yaml
      tags: bwa, transcriptomics
      
    - include: software_tasks/samtools.yaml version=1.3.1
      tags: samtools, transcriptomics

    - include: software_tasks/bcftools.yaml version=1.3.1
      tags: bcftools, transcriptomics
      
    - name: Installing blast legacy & blast+
      apt: name={{item}} state=present
      with_items:
       - ncbi-blast+
       - ncbi-blast+-legacy
       - ncbi-tools-bin
       - ncbi-tools-x11
      tags: blast
      
    - name: Installing EMBOSS tools (getorf)
      apt: name={{item}} state=present
      with_items:
       - emboss
       - emboss-data
       - emboss-doc
       - emboss-lib
       - jemboss
      tags: emboss
      
    - name: Installing FastTree2
      apt: name=fasttree state=present
      tags: fasttree
    - name: Install FastTree2 Links
      file: src=/usr/bin/fasttree dest=/usr/bin/FastTree state=link
      tags: fasttree
    - name: Install FastTree2 MP Links
      file: src=/usr/bin/fasttreeMP dest=/usr/bin/FastTreeMP state=link
      tags: fasttree
      
    - include: software_tasks/igv.yaml version=2.3.80
      tags: genomics, igv, transcriptomics
    - include: software_tasks/igvtools.yaml version=2.3.80
      tags: igvtools, transcriptomics
      
    - name: Install bedtools
      apt: name=bedtools state=present
      tags: bedtools

    - include: software_tasks/qualimap.yaml version=2.2
      tags: qualimap

    - include: software_tasks/SPAdes.yaml version=3.11.0
      tags: spades

    - include: software_tasks/quast.yaml version=4.5
      tags: quast

    - include: software_tasks/hmmer.yaml version=3.1b2
      tags: genomics, hmmer

    - name: Installing Velvet Assembler
      apt: name={{item}} state=present
      with_items:
       - velvet
       - velvet-example
      tags: velvet

    - include: software_tasks/bam2fastq.yaml version=1.1.0
      tags: bam2fastq

    - include: software_tasks/newick_utils.yaml
      tags: newick_utils


    ### Other R Prerequisites ###
    ## Previously Installed
    # r and r studio server/desktop

    - name: Installing littler
      apt: name=r-cran-littler state=present
      tags: r, phyloseq, littler

    - name: Installing ggplot2
      shell: "{{playbook_dir}}/scripts/install.r ggplot2"
      tags: r, ggplot2

    - include: software_tasks/jupyter.yaml
      tags: r, jupyter
    

    ### Transcriptomics ###
    ## Previously Installed
    # bowtie1, bioconductor, IGV, igvtools, samtools, gmap

    - include: software_tasks/r_transcriptomics.yaml
      tags: r, transcriptomics, differential

    - include: software_tasks/rsem.yaml version=1.2.31
      tags: transcriptomics, rsem
    
    - name: Installing xpdf and lighttpd
      apt: name="{{item}}" state=present
      with_items:
        - xpdf
        - lighttpd
      tags: transcriptomics

    - include: software_tasks/trinity.yaml
      tags: trinity, transcriptomics

    - include: software_tasks/trinotate.yaml
      tags: transcriptomics, trinotate, transdecoder

    - include: software_tasks/cbs_programs.yaml
      tags: trinity, cbs, signalp, tmhmm, rnammer, transcriptomics

    - name: Installing MultiQC
      pip: name=multiqc state=present
      tags: transcriptomics

    - include: software_tasks/hisat2.yaml version=2.1.0
      tags: hisat2, transcriptomics

    - include: software_tasks/stringtie.yaml version=1.3.3b
      tags: stringtie, transcriptomics


    ### Differential Expression ###
    ## Previously Installed
    # git, sra-toolkit, r, rstudio, ggplot2, goseq

    - include: software_tasks/r_differential_expression.yaml
      tags: r, differential


    ### Single Cell Transcriptomics
    ## Previously Installed
    # some R stuff I guess

    - include: software_tasks/r_singlecell.yaml
      tags: r, singlecell

    - include: software_tasks/pagoda2.yaml
      tags: pagoda2, singlecell

    - name: Installing urltools
      shell: "{{playbook_dir}}/scripts/install.r Seurat"
      tags: seurat, singlecell

  ## Finishing Touches
  post_tasks:  
    - name: Changing software/source user:group to {{workshop_user}}:workshop
      file: path=/home/{{workshop_user}}/software owner={{workshop_user}} group=workshop recurse=yes
      tags: finish

    - shell: echo 'Now please run the {{workshop_user}} Workshop Data Tasks Playbook'
      tags: finish
