- hosts: all
  become: yes
  vars:
    - workshop_user: transcriptomics
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - software_dir: "/home/{{workshop_user}}/software"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"

  tasks:
  ### Common ###

  ### Transcriptomics ###

  - name: Create Transcriptomics Directory
    file: path="{{workshop_dir}}/transcriptomics" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - name: Create Trinotate databases Directory
    file: path="{{workshop_dir}}/transcriptomics/trinotate_databases" state=directory owner="{{workshop_user}}" group=workshop
    tags: transcriptomics

  - include: data_tasks/swissprot.yaml
    tags: transcriptomics, swissprot

  - include: data_tasks/pfam.yaml
    tags: transcriptomics, pfam

  - include: data_tasks/trinotate.yaml
    tags: transcriptomics, trinotate

  - name: Cloning Trinity Workshop
    git: repo=https://github.com/trinityrnaseq/RagonInst_Sept2017_Workshop.git dest="{{workshop_dir}}/transcriptomics/RagonInst_Sept2017_Workshop" clone=yes update=yes
    become: true
    become_user: "{{workshop_user}}"
    tags: transcriptomics

